version: 0.2

phases:
  build:
    commands:
      - echo "Preparing Lambda package"
      - ls
      - zip -r function.zip lambda_function.py
      - echo "Checking ZIP contents"
      - unzip -l function.zip

artifacts:
  files:
    - function.zip
