version: 0.2

phases:
  build:
    commands:
      - echo "Zipping code"
      - zip function.zip lambda_function.py
      - echo "Updating Lambda"
      - aws lambda update-function-code \
        --function-name today-my-lambda-function \
        --zip-file fileb://function.zip
